---
abstract: 'Change passwords on UNIX and UNIX-like servers on a simple, '
author:
  - 'Claudio Ramirez <nxadm@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::More: 0.42
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-Unix-RPasswd
no_index:
  directory:
    - inc
    - lib/App/Unix/RPasswd
    - t
requires:
  Crypt::PasswdMD5: 0
  Expect: 0
  List::MoreUtils: 0
  Moo: 0
  Term::ReadKey: 0

  Parallel::ForkManager: 0
  perl: 5.10.0
resources:
  license: http://opensource.org/licenses/gpl-license.php
version: 0.52
