---
abstract: 'Change passwords on UNIX and UNIX-like servers on a simple, '
author:
  - 'Claudio Ramirez, C<< <nxadm at cpan.org> >>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-Unix-RPasswd
no_index:
  directory:
    - inc
    - lib/App/Unix/RPasswd
    - t
requires:
  Crypt::PasswdMD5: 0
  DateTime: 0
  Expect: 0
  List::MoreUtils: 0
  Moose: 0
  Parallel::ForkManager: 0
  namespace::autoclean: 0
  perl: 5.10.0
resources:
  license: http://opensource.org/licenses/gpl-license.php
version: 0.31
