---
abstract: "Change passwords on UNIX and UNIX-like servers on a simple, \nfast (in parallel) and secure (SSH) way."
author:
  - 'Claudio Ramirez <nxadm@cpan.org>'
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.110580'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-Unix-RPasswd
provides:
  App::Unix::RPasswd:
    file: lib/App/Unix/RPasswd.pm
    version: 0.3
  App::Unix::RPasswd::Connection:
    file: lib/App/Unix/RPasswd/Connection.pm
    version: 0.3
  App::Unix::RPasswd::SaltedPasswd:
    file: lib/App/Unix/RPasswd/SaltedPasswd.pm
    version: 0.3
requires:
  Crypt::PasswdMD5: 0
  DateTime: 0
  Expect: 0
  File::Basename: 0
  Getopt::Long: 0
  List::MoreUtils: 0
  Moose: 0
  Parallel::ForkManager: 0
  namespace::autoclean: 0
  perl: v5.10.0
resources:
  license: http://opensource.org/licenses/gpl-license.php
version: 0.3
